version: "3.7"

services:
  postgres:
    image: postgres:bullseye
    # container_name: docker_name_for_db
    ports:
      - 1234:5432
    environment:
      - POSTGRES_DB=school
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
